apiVersion: apps/v1             # Versión de kubernetes
kind: Deployment                # Tipo de Objeto 
metadata:                       # Información adicional
  name: dpt-vaccine-back         # Nombre del despliegue
  namespace: vaccineapi
spec:                           # Especificaciones del despliegue
  replicas: 1                   # Número de replicas que tendrá este pod
  selector:                     # Es la forma primitiva de hacer referencia, es como un id interno
    matchLabels:                # 
      app: vaccine-back-app           # Etiqueta para que otros objetos de kubernetes lo encuentren
  template:                     # Es la configuración final del pod 
    metadata:                   # Tiene su propia metadata para la plantilla o pod
      labels:                   # 
        app: vaccine-back-app          # Etiqueta del contenedor
    spec:                       # Tiene sus especificaciones
      containers:               # Información del contenedors o mas si el pod tiene muchos
      - name: vaccine-back-app          # Nombre del contenedor
        image: gcr.io/kubernetes-sd-323304/newvaccineback      # url de imagen, docker hub defautl
        ports:                  # puertos
        - containerPort: 8080
        env:
        - name: MONGODB_HOSTNAME
          value: mongodb-0.mongodb-headless.database
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: liberty
        - name: MONGODB_USERNAME
          value: admin
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: creds
              key: db-password
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi