apiVersion: v1
kind: Service
metadata:
  name: drage
  namespace: vaccineapi
spec:
  type: NodePort
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: drage