apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: database
type: Opaque
data:
  mongodb-root-password: ccGFzc3dvcmQ= #password
  mongodb-password: ccGFzc3dvcmQ= #password
  mongodb-replica-set-key: ccGFzc3dvcmQ= #password