apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-standalone
  namespace: vaccineapi
spec:
  serviceName: vaccineapi
  replicas: 1
  selector:
    matchLabels:
      app: vaccineapi
  template:
    metadata:
      labels:
        app: vaccineapi
        selector: backend-standalone
    spec:
      containers:
      - name: backend-standalone
        image: gcr.io/kubernetes-sd-323304/newvaccineback
        env:
        - name: MONGODB_HOSTNAME
          value: mongodb-0.mongodb-headless.database
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: liberty
        - name: MONGODB_USERNAME
          value: admin
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: creds
              key: db-password
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      